# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
[en]
  languageCode = "en-us"
  contentDir = "content/en"  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  staticDir= "static"
  title = "Covid-19 Mobility Project"
  
# Configure the German version.
[de]
  languageCode = "de"
  contentDir = "content/de"
  staticDir = "static"
  title = "Covid-19 Mobility Project"
  [de.params]
    description = "Projekt Mobility Monitor von Humboldt Universität und Robert Koch-Institut, gefördert durch das Bundesgesundheitsministerium"
    keywords = "Covid, Mobilitätsdaten, Frank Schlosser, Mobilität in Deutschland, Prof. Dr. Dirk Brockmann, Complex Systems, Komplexe Systeme, HU Berlin, Prof. Brockmann, Dirk Brockmann"
    copyright = "&copy; Forschungsgruppe P4 Robert Koch-Institut, Prof. Dr. Dirk Brockmann"
    # office_hours = ["10:00 bis 16:00 Montag bis Freitag"]
    office_hours = []

