# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Mobilität"
  url = "mobility-monitor"
  weight = 10

[[main]]
  name = "Kontakte"
  url = "contact-index"
  weight = 20

[[main]]
  name = "News"
  url = "#news"
  weight = 30

[[main]]
  name = "Reports"
  url = "reports"
  weight = 40

[[main]]
  name = "Daten und Methoden"
  url = "data-info"
  weight = 50

[[main]]
  name = "Mobilität"
  identifier = "Mobilität Methodik"
  pre = ""
  url = "data-info"
  parent = "Daten und Methoden"
  weight = 5

[[main]]
  name = "Kontakte"
  identifier = "Kontakte Methodik"
  pre = ""
  url = "data-info/contacts"
  parent = "Daten und Methoden"
  weight = 10

[[main]]
  name = "Import Risiko"
  identifier = "import_risk-methods"
  pre = ""
  url = "data-info/import_risk"
  parent = "Daten und Methoden"
  weight = 15

[[main]]
  name = "Team"
  url = "#people"
  weight = 60

[[main]]
  name = "Kontakt"
  url = "#contact"
  weight = 70
